import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Share, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { ArrowLeft, Download, Share2 } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Card } from '../../components/ui/Card';
import { useTheme } from '../../lib/theme';
import { useReport, useShareReport } from '../../features/reports/hooks/useReports';
import type { MonthlyReport, WeeklyReport } from '../../schemas/reports';

// Builds a minimal, self-contained HTML string for expo-print. No external
// resources — everything inline so the PDF renders offline.
function buildReportHtml(report: WeeklyReport | MonthlyReport): string {
  const isMonthly = report.period === 'monthly';
  const title = isMonthly ? 'Monthly Report' : 'Weekly Report';
  const period = `${report.period_start} – ${report.period_end}`;
  const score = report.score ?? 'N/A';

  let achievementsHtml = '';
  let insightsHtml = '';
  let narrative = '';

  if (report.period === 'weekly') {
    const s = report.summary;
    narrative = s.narrative;
    achievementsHtml = s.achievements.length > 0
      ? `<h3>Achievements</h3><ul>${s.achievements.map((a) => `<li>${a}</li>`).join('')}</ul>`
      : '';
    insightsHtml = s.improvement_areas.length > 0
      ? `<h3>Areas to improve</h3><ul>${s.improvement_areas.map((a) => `<li>${a}</li>`).join('')}</ul>`
      : '';
  } else {
    const s = report.summary;
    narrative = s.narrative;
    insightsHtml = s.insights.length > 0
      ? `<h3>Insights</h3><ul>${s.insights.map((i) => `<li>${i}</li>`).join('')}</ul>`
      : '';
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  body { font-family: -apple-system, sans-serif; margin: 32px; color: #14201b; }
  h1 { color: #12a06a; font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 18px; color: #14201b; margin: 24px 0 8px; }
  h3 { font-size: 14px; color: #14201b; margin: 16px 0 4px; }
  .period { color: #5c6b63; font-size: 13px; }
  .score { font-size: 56px; font-weight: bold; color: #12a06a; text-align: center; }
  .narrative { font-size: 15px; line-height: 1.6; color: #14201b; }
  ul { padding-left: 20px; }
  li { margin-bottom: 4px; font-size: 14px; }
  .footer { margin-top: 40px; font-size: 11px; color: #9db0a6; }
</style></head><body>
<h1>Saathi — ${title}</h1>
<p class="period">${period}</p>
<div class="score">${score}</div>
<p class="narrative">${narrative}</p>
${achievementsHtml}
${insightsHtml}
<p class="footer">Generated by Saathi. This is not a medical report. Numbers computed on-device from your logs.</p>
</body></html>`;
}

function ScoreChip({ score }: { score: number | null }) {
  const { tokens } = useTheme();
  if (score === null) return null;
  return (
    <View className="items-center">
      <Text style={{ color: tokens.primary }} className="font-display text-5xl">{score}</Text>
      <Text className="font-body text-xs text-ink-muted">/ 100</Text>
    </View>
  );
}

function WeeklyContent({ report }: { report: WeeklyReport }) {
  const s = report.summary;
  return (
    <>
      <Card className="gap-2">
        <Text className="font-body-semibold text-sm text-ink">Week at a glance</Text>
        <Text className="font-body text-sm text-ink">{s.narrative}</Text>
      </Card>
      <View className="flex-row gap-3">
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Steps</Text>
          <Text className="font-body-semibold text-base text-ink">{s.totals.steps.toLocaleString()}</Text>
        </Card>
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Workouts</Text>
          <Text className="font-body-semibold text-base text-ink">{s.totals.workoutCount}</Text>
        </Card>
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Avg sleep</Text>
          <Text className="font-body-semibold text-base text-ink">{s.totals.sleepAvgHours}h</Text>
        </Card>
      </View>
      {s.achievements.length > 0 ? (
        <Card className="gap-2">
          <Text className="font-body-semibold text-sm text-ink">Achievements</Text>
          {s.achievements.map((a, i) => (
            <Text key={i} className="font-body text-sm text-ink">• {a}</Text>
          ))}
        </Card>
      ) : null}
      {s.improvement_areas.length > 0 ? (
        <Card className="gap-2">
          <Text className="font-body-semibold text-sm text-ink">Areas to improve</Text>
          {s.improvement_areas.map((a, i) => (
            <Text key={i} className="font-body text-sm text-ink-muted">• {a}</Text>
          ))}
        </Card>
      ) : null}
    </>
  );
}

function MonthlyContent({ report }: { report: MonthlyReport }) {
  const s = report.summary;
  const trend = s.score_trend === 'improving' ? '↑' : s.score_trend === 'declining' ? '↓' : '→';
  return (
    <>
      <Card className="gap-2">
        <View className="flex-row items-center gap-2">
          <Text className="font-body-semibold text-sm text-ink">Month overview</Text>
          <Text className="font-body-medium text-xs text-ink-muted">{trend} {s.score_trend}</Text>
        </View>
        <Text className="font-body text-sm text-ink">{s.narrative}</Text>
      </Card>
      <View className="flex-row gap-3">
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Avg steps</Text>
          <Text className="font-body-semibold text-sm text-ink">{s.averages.steps.toLocaleString()}</Text>
        </Card>
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Avg sleep</Text>
          <Text className="font-body-semibold text-sm text-ink">{s.averages.sleepHours}h</Text>
        </Card>
        <Card className="flex-1 gap-1">
          <Text className="font-body text-xs text-ink-muted">Avg water</Text>
          <Text className="font-body-semibold text-sm text-ink">{s.averages.waterL}L</Text>
        </Card>
      </View>
      {s.current_weight_kg !== null ? (
        <Card className="flex-row justify-between">
          <Text className="font-body text-sm text-ink">Weight</Text>
          <View className="items-end">
            <Text className="font-body-semibold text-sm text-ink">{s.current_weight_kg} kg</Text>
            {s.weight_change_kg !== null ? (
              <Text className="font-body text-xs text-ink-muted">
                {s.weight_change_kg > 0 ? '+' : ''}{s.weight_change_kg} kg vs last month
              </Text>
            ) : null}
          </View>
        </Card>
      ) : null}
      {s.insights.length > 0 ? (
        <Card className="gap-2">
          <Text className="font-body-semibold text-sm text-ink">Insights</Text>
          {s.insights.map((insight, i) => (
            <Text key={i} className="font-body text-sm text-ink">• {insight}</Text>
          ))}
        </Card>
      ) : null}
    </>
  );
}

export default function ReportScreen() {
  const router = useRouter();
  const { tokens } = useTheme();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { data: report, isLoading } = useReport(id);
  const shareReport = useShareReport();
  const [exporting, setExporting] = useState(false);

  async function handleExportPdf() {
    if (!report) return;
    setExporting(true);
    try {
      const html = buildReportHtml(report);
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `Saathi ${report.period === 'monthly' ? 'Monthly' : 'Weekly'} Report`,
        });
      } else {
        Alert.alert('PDF saved', `Saved to: ${uri}`);
      }
    } catch {
      Alert.alert('Export failed', 'Could not generate the PDF. Try again.');
    } finally {
      setExporting(false);
    }
  }

  async function handleShareLink() {
    if (!report || report.period !== 'monthly') return;
    try {
      const token = await shareReport.mutateAsync(report.id);
      const url = `https://saathi.app/share/${token}`;
      await Share.share({ message: url, url });
    } catch {
      Alert.alert('Could not create share link', 'Please try again.');
    }
  }

  if (isLoading || !report) {
    return (
      <SafeAreaView className="flex-1 bg-canvas" edges={['top', 'bottom']}>
        <View className="flex-1 items-center justify-center">
          <ActivityIndicator />
        </View>
      </SafeAreaView>
    );
  }

  const isMonthly = report.period === 'monthly';
  const title = isMonthly ? 'Monthly Report' : 'Weekly Report';

  return (
    <SafeAreaView className="flex-1 bg-canvas" edges={['top', 'bottom']}>
      {/* Header */}
      <View className="flex-row items-center justify-between px-5 pb-2 pt-4">
        <Pressable
          onPress={() => router.back()}
          className="min-h-[44px] min-w-[44px] items-center justify-center"
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <ArrowLeft size={22} color={tokens.ink} strokeWidth={2} />
        </Pressable>
        <Text className="font-body-semibold text-base text-ink">{title}</Text>
        <View className="flex-row gap-2">
          {isMonthly ? (
            <Pressable
              onPress={handleShareLink}
              disabled={shareReport.isPending}
              className="min-h-[44px] min-w-[44px] items-center justify-center"
              accessibilityRole="button"
              accessibilityLabel="Copy share link"
            >
              {shareReport.isPending
                ? <ActivityIndicator size="small" />
                : <Share2 size={20} color={tokens.ink} strokeWidth={2} />}
            </Pressable>
          ) : null}
          <Pressable
            onPress={handleExportPdf}
            disabled={exporting}
            className="min-h-[44px] min-w-[44px] items-center justify-center"
            accessibilityRole="button"
            accessibilityLabel="Export PDF"
          >
            {exporting
              ? <ActivityIndicator size="small" />
              : <Download size={20} color={tokens.ink} strokeWidth={2} />}
          </Pressable>
        </View>
      </View>

      <ScrollView
        contentContainerClassName="px-5 pb-8 gap-4"
        showsVerticalScrollIndicator={false}
      >
        <View className="items-center gap-1 py-2">
          <ScoreChip score={report.score} />
          <Text className="font-body text-xs text-ink-muted">
            {report.period_start} – {report.period_end}
          </Text>
        </View>

        {report.period === 'weekly'
          ? <WeeklyContent report={report} />
          : <MonthlyContent report={report} />}

        <Text className="text-center font-body text-xs text-ink-muted">
          Numbers computed from your logs. This is not a medical report.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}
