import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { monthlyGoalSchema, type MonthlyGoal } from '../../../schemas/goals';
import { supabase } from '../../../lib/supabase';
import { useSession } from '../../auth/SessionProvider';
import { todayDateString } from '../../journal/hooks/useDailyLog';

const SELECT_GOALS = 'id, user_id, month, target_weight_kg, daily_step_goal, sleep_goal_hours, water_goal_l, protein_goal_g, workout_goal_per_week, sugar_reduction_note, rationale, created_at';

function currentMonthStart(): string {
  return `${todayDateString().slice(0, 7)}-01`;
}

function previousMonthEnd(): string {
  const start = new Date(`${currentMonthStart()}T00:00:00Z`);
  start.setUTCDate(start.getUTCDate() - 1);
  return start.toISOString().slice(0, 10);
}

export function goalsQueryKey(userId: string | undefined, month: string) {
  return ['goals', userId, month] as const;
}

// Current month's goals — the row generated by goal-generator at the end of
// last month using last month's pace. Returns null if goals haven't been
// generated yet.
export function useCurrentGoals() {
  const { session } = useSession();
  const userId = session?.user.id;
  const month = currentMonthStart();

  return useQuery({
    queryKey: goalsQueryKey(userId, month),
    queryFn: async (): Promise<MonthlyGoal | null> => {
      const { data, error } = await supabase
        .from('goals')
        .select(SELECT_GOALS)
        .eq('user_id', userId)
        .eq('month', month)
        .maybeSingle();
      if (error) throw error;
      if (!data) return null;
      return monthlyGoalSchema.parse(data);
    },
    enabled: !!userId,
  });
}

// On-demand fallback — generates goals for next month based on this month's
// data so far. Called when a user checks the Goals section before the cron
// has run (or from the Insights tab "generate goals" prompt).
export function useGenerateGoals() {
  const { session } = useSession();
  const userId = session?.user.id;
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (): Promise<MonthlyGoal> => {
      const periodEnd = previousMonthEnd();
      const { data, error } = await supabase.functions.invoke('goal-generator', {
        body: { period_end: periodEnd },
      });
      if (error) throw error;
      return monthlyGoalSchema.parse(data);
    },
    onSuccess: (data) => {
      queryClient.setQueryData(goalsQueryKey(userId, data.month), data);
    },
  });
}
